import { ProductType } from '../types/ProductType';

export const productsDB: ProductType[] = [
  { id: '1', name: 'Interruptor 4x2 1B', price: 74.95, category: 'Interruptor-Tomadas' },
  { id: '2', name: 'Interruptor 4x2 2B', price: 78.99, category: 'Interruptor-Tomadas' },
  { id: '3', name: 'Interruptor 4x2 3B', price: 68.72, category: 'Interruptor-Tomadas' },
  { id: '4', name: 'Interruptor 4x2 4B', price: 99.99, category: 'Interruptor-Tomadas' },
  { id: '5', name: 'Interruptor 4x4 4B', price: 139.99, category: 'Interruptor-Tomadas' },
  { id: '6', name: 'Interruptor 4x4 6B', price: 165.99, category: 'Interruptor-Tomadas' },
  { id: '7', name: 'Interruptor 4x4 8B', price: 209.99, category: 'Interruptor-Tomadas' },
  { id: '8', name: 'Interruptor 4x2 1B + 1T', price: 130, category: 'Interruptor-Tomadas' },
  { id: '9', name: 'Interruptor 4x2 1B + 2T', price: 0, category: 'Interruptor-Tomadas' },
  { id: '10', name: 'Interruptor 4x2 2B + 1T', price: 144.99, category: 'Interruptor-Tomadas' },
  { id: '11', name: 'Interruptor 4x4 4B + 2T', price: 174.99, category: 'Interruptor-Tomadas' },
  { id: '12', name: 'Controle ventilador smart', price: 0, category: 'Interruptor-Tomadas' },
  { id: '13', name: 'Sonoff mini', price: 0, category: 'Interruptor-Tomadas' },
  { id: '14', name: 'Interruptor R2 2S', price: 39.99, category: 'Interruptor-Tomadas' },
  { id: '15', name: 'Interruptor R2 3S', price: 69, category: 'Interruptor-Tomadas' },
  { id: '16', name: 'Interrutor paralelo RF433 2B', price: 49.99, category: 'Interruptor-Tomadas' },
  { id: '17', name: 'Tomada sobrepor wifi 10A', price: 49.99, category: 'Interruptor-Tomadas' },
  { id: '18', name: 'Tomada sobrepor wifi 16A', price: 61.36, category: 'Interruptor-Tomadas' },
  { id: '19', name: 'Tomada embutir 20A 1T', price: 119.99, category: 'Interruptor-Tomadas' },
  { id: '20', name: 'Interruptor cortina', price: 124.99, category: 'Interruptor-Tomadas' },
  { id: '21', name: 'Tomada c/USB 2S', price: 165.51, category: 'Interruptor-Tomadas' },
  { id: '22', name: 'Lampada Led', price: 0, category: 'Iluminação' },
  { id: '23', name: 'Lampada Led RGB', price: 39.54, category: 'Iluminação' },
  { id: '24', name: 'Fita Led', price: 0, category: 'Iluminação' },
  { id: '25', name: 'Fita led RGB 10m', price: 169.99, category: 'Iluminação' },
  { id: '26', name: 'Fita Led RGB 5m', price: 31.5, category: 'Iluminação' },
  { id: '27', name: 'Plafon Led Embutir', price: 0, category: 'Iluminação' },
  { id: '28', name: 'Plafon led RGB Embutir 18w redondo', price: 139.32, category: 'Iluminação' },
  { id: '29', name: 'Plafon led RGB Embutir 24w redondo', price: 144.99, category: 'Iluminação' },
  { id: '30', name: 'Plafon Led Sobrepor', price: 0, category: 'Iluminação' },
  { id: '31', name: 'Plafon led RGB Sobrepor 24w quadrado', price: 170.45, category: 'Iluminação' },
  { id: '32', name: 'Plafon led RGB Sobrepor 18w redondo', price: 119.99, category: 'Iluminação' },
  { id: '33', name: 'Plafon led RGB Sobrepor 18w quadrado', price: 129.99, category: 'Iluminação' },
  { id: '34', name: 'Barra Led', price: 0, category: 'Iluminação' },
  { id: '35', name: 'Controlador dual rgb fita led', price: 49.99, category: 'Iluminação' },
  { id: '36', name: 'Spot RGB redondo embutir', price: 59.09, category: 'Iluminação' },
  { id: '37', name: 'Roteador Unifi Dream Router', price: 1800, category: 'Roteador' },
  { id: '38', name: 'Roteador Mesh', price: 1400, category: 'Roteador' },
  { id: '39', name: 'Acess point ubiquit', price: 1200, category: 'Roteador' },
  { id: '40', name: 'Hub 3.0', price: 173.99, category: 'Roteador' },
  { id: '41', name: 'Roteador Mesh Twibi', price: 459, category: 'Roteador' },
  { id: '42', name: 'Cartão memória 128GB', price: 0, category: 'Cartão de Memória' },
  { id: '43', name: 'Cartão memória 256GB', price: 410, category: 'Cartão de Memória' },
  { id: '44', name: 'Cartão memória 512GB', price: 0, category: 'Cartão de Memória' },
  { id: '45', name: 'Cartão memória 1TB', price: 0, category: 'Cartão de Memória' },
  { id: '46', name: 'fechadura digital', price: 349, category: 'Segurança' },
  { id: '47', name: 'camera wifi', price: 167.2, category: 'Segurança' },
  { id: '48', name: 'fechadura digital', price: 650, category: 'Segurança' },
  { id: '49', name: 'video porteiro', price: 349.99, category: 'Segurança' },
  { id: '50', name: 'controle remoto IR smart', price: 48.99, category: 'Controle IR' },
  { id: '51', name: 'Sensor porta e janela rf433', price: 32.9, category: 'Sensores' },
  { id: '52', name: 'Detector fumaça rf433', price: 72.99, category: 'Sensores' },
  { id: '53', name: 'Sensor presença wifi', price: 74.25, category: 'Sensores' },
  { id: '54', name: 'Sensor temperatura', price: 249.99, category: 'Sensores' },
  { id: '55', name: 'Módulo mini cortina', price: 73, category: 'Cortinas' },
  { id: '56', name: 'motor tubular cortina de rolo', price: 459.99, category: 'Cortinas' },
  { id: '57', name: 'cortina motorizada 4,2m', price: 923.99, category: 'Cortinas' },
  { id: '58', name: 'controle de cenas', price: 104.4, category: 'Outros' },
  { id: '59', name: 'eletrofita 10A', price: 25, category: 'Outros' },
  { id: '60', name: 'eletrofita 20A', price: 74, category: 'Outros' },
  { id: '61', name: 'Echo dot', price: 300, category: 'Assistentes' },
  { id: '62', name: 'Echo show', price: 800, category: 'Assistentes' },
];
